[project]
name = "comfyui-minimal-prometheus-exporter"
version = "1.0.0"
description = "Prometheus metrics exporter for ComfyUI with minimal dependencies and data gathered"
license = { file = "LICENSE" }
requires-python = ">=3.10"
readme = "README.md"
dependencies = ["prometheus-client"]

[project.urls]
Repository = "https://github.com/druggeri/ComfyUI-Minimal-Prometheus-Exporter"

[tool.comfy]
PublisherId = "druggeri"
DisplayName = "ComfyUI Minimal Prometheus Exporter"
